Python 3.6 Nvidia K40:
  script:
  - export PY_EXE=python3.6
  - export PYOPENCL_TEST=nvi:k40
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.6
  - nvidia-k40
  except:
  - tags

Python 2.7 POCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako mpi4py"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  - mpi
  except:
  - tags

Python 3.6 POCL:
  script:
  - export PY_EXE=python3.6
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako mpi4py"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.6
  - pocl
  - mpi
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh meshmode test"
  tags:
  - python3.5
  except:
  - tags
